module.exports = {
    DB_CONNECTION_SUCCESS: "Database connection successful.",
    DB_CONNECTION_ERROR: "Database connection failed.",
    DB_IDLE_CONNECTION_ERROR: "Unexpected error on idle client",
    GET_ERROR: "Failed to get data from the Database.",
    USER_FOUND:"User found",
    USER_NOT_FOUND:"User not found",
    USER_ALREADY_EXISTS:"User already exists",
    UPDATE_ERROR: "Record could not be updated.",
    INSERT_ERROR: "Record could not be inserted.",
    UPDATE_SUCCESS: "Record(s) Updated Successfully.",
    UPDATE_FAILED:"Record(s) Updation Failed",
    DELETE_ERROR: "Record could not be deleted.",
    DELETE_SUCCESS: "Records Deleted Successfully.",
    INSERT_SUCCESS: "Record created successfully.",
    STATUS_SUCCESS: "SUCCESS",
    STATUS_FAILED: "FAILED",
    INVALID_USERNAME: "Access denied. User Name is invalid.",
    USERNAME_INVALID: "Reason- User Name is invalid.",
    LOG_INFORMATION: "INFO",
    LOG_DEBUG: "DEBUG",
    LOG_ERROR: "ERROR",
    LOG_WARNING: "WARN",
    LOG_DELETE: "DELETE",
    SERVER_START:"Server is listening on port",
    REQUEST_DATA_NOT_FOUND:"Request data not found",
    INTERNAL_SERVER_ERROR:"Internal server error",
    USER_UNAUTHORIZED:'User is unauthorized to login on this portal',
    GET_SUCCESS:'Record fetched successfully',
    RECORD_NOT_FOUND:'Record not found ',
    INVALID_EMPLOYEE_ID:"Invalid Employee Id",
    CANNOT_REPORT_ISSUE:"Cannot report issue",
    NEW_ISSUE_RAISED:' : Issue Raised',
    NEW_ISSUE_RAISED_BY:' And Raised by: '

  }
  